production:
  adapter: redis
  url: redis://redistogo:b0a15af3a4f5b0d248e3159888e00d84@sculpin.redistogo.com:9105/

development: &development
  adapter: redis
  url: redis://cache:6379

test:
  <<: *development

