development: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  database: toiletraffic_development
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: toiletraffic_test

production:
 <<: *default
