development: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  database: toiletraffic_development
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

test:
  <<: *default
  database: toiletraffic_test

production:
 <<: *default
